export * as AP from "fp-ts/Apply";
export * as E from "fp-ts/Either";
export * as FN from "fp-ts/function";
export * as O from "fp-ts/Option";
export * as RA from "fp-ts/ReadonlyArray";
export * as T from "fp-ts/Task";
export * as TE from "fp-ts/TaskEither";
export * as IO from "fp-ts/IO";
export * as s from "fp-ts/string"
export * as RR from "fp-ts/ReadonlyRecord";
export * as RNEA from "fp-ts/ReadonlyNonEmptyArray";