export * as AP from "fp-ts/lib/Apply";
export * as E from "fp-ts/lib/Either";
export * as FN from "fp-ts/lib/function";
export * as O from "fp-ts/lib/Option";
export * as RA from "fp-ts/lib/ReadonlyArray";
export * as T from "fp-ts/lib/Task";
export * as TE from "fp-ts/lib/TaskEither";
export * as IO from "fp-ts/lib/IO";
export * as s from "fp-ts/lib/string"
export * as RR from "fp-ts/lib/ReadonlyRecord";
export * as RNEA from "fp-ts/lib/ReadonlyNonEmptyArray";